### ISSUE TITLE
Error reading file: ENOENT: no such file or directory when other root is set 

### ISSUE THREAD

**Issue by norixx** [vHeemstra/vite-plugin-imagemin#19]
My project settings are a little different from normal, but they look like this.

```
vite-project
├── dist
├── src
│   ├── about.html
│   ├── assets
│   │   ├── img
│   │   │   ├── image01.jpg, ....
│   │   │   ├── javascript.svg
│   │   │   └── sub01
│   │   │       └── sub01.png, ...
│   │   └── js
│   │       └── some.js
│   ├── index.html
│   ├── main.js
│   ├── public
│   │   └── vite.svg
│   ├── style.css
│   └── test
│       └── test.html
├── tailwind.config.js
└── vite.config.js

```
All the resource files are in src folder. 

vite.config.js
```
import { defineConfig } from "vite";
import { resolve } from "path";
import { glob } from "glob";
import imagemin from '@vheemstra/vite-plugin-imagemin'
import imageminWebp from 'imagemin-webp'
import imageminMozjpeg from 'imagemin-mozjpeg'
import imageminPngquant from 'imagemin-pngquant'

...

export default defineConfig({
  root: './src',
  build: {
    outDir: '../dist',
    emptyOutDir: true,
    sourcemap: true,
    rollupOptions: {
      input: getHtmlInputs(),
      output: {
        // some config
  },

  plugins: [
    imagemin({
      root: './src', // This didn't help 
      plugins: {
        jpg: imageminMozjpeg(),
        png: imageminPngquant(),
...
```
As long as I don't specify `src` or `outputDir` in vite.config.js, there is no problem with image compression or conversion to WebP, but if I set it up as above, it throws an error.

> Error reading file [ENOENT: no such file or directory, open '/Users/someuser/my_sandbox/vite-project/src//Users/someuser/my_sandbox/vite-project/dist/assets/img/sub01/sub01.png']

I also used the `root` option, but it still gives the same error result.
Is there any way to fix this? Thank you in advance for your help.

**Comment by lattaai8** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the plugin to correctly handle custom root directories specified in Vite configuration. This should resolve the issue where the plugin was unable to find image files when a custom root directory was set.

You can review changes in this commit: https://github.com/lattaai8/vHeemstra-vite-plugin-imagemin-19/commit/fab659124158331241835c59234acbfa7e620ebf.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by vHeemstra** [comment]
Can you set up an online minimal example where this error happens (using CodeSandbox.io or similar)? Then I can take a better look at what is happening.

FYI: The `root` option should point to the project's root folder, not the `src` folder within that. This might be why the error occurs.

**Comment by norixx** [comment]
@vHeemstra I set up the simple example in codesandbox, so you can take a look at it.
https://codesandbox.io/p/github/norixx/vite-multipage-project/main
Thanks.

**Comment by norixx** [comment]
Any follow up?

**Comment by vHeemstra** [comment]
@norixx The problem is with your config of the vite-imagemin-plugin.

**Solution:**
The `root` option for the plugin should point to your projects root directory, in your case: `'./'`.

For completeness, omitting it will have it default to the value of your `defineConfig`'s root option, which is also the incorrect value `'./src/'`.

_Side note:_
In your Vite config there are also 2 non-existing options declared for the plugin:
* `mode: 'multiple'`
* `filter: /\.(jpe?g|png)$/i`

**Comment by norixx** [comment]
It's such a simple way to solve the problem. It was output properly.
Thank you!
