### ISSUE TITLE
make* plugins: inconsistent building

### ISSUE THREAD

**Issue by NamesMT** [vHeemstra/vite-plugin-imagemin#3]
Configs:
```
viteImagemin({
        plugins: {
          jpg: imageminMozjpeg(),
          png: imageminPngquant(),
        },
        makeWebp: (true || mode === 'webp')
          ? {
              skipIfLargerThan: 'smallest',
              plugins: {
                jpg: imageminWebp({
                  method: 6,
                  quality: 100,
                }),
                png: imageminWebp({
                  method: 6,
                  quality: 100,
                }),
              },
            }
          : undefined,
      }),
```

Webp randomly doesn't build for some files (Red2.png, Yellow1.png,...)

![image](https://user-images.githubusercontent.com/23612546/219540343-b10adf6b-6546-4f86-bf8b-13c624470b04.png)

**Comment by NamesMT** [comment]
Close:
Its actually because they're skipped, and echoing at the bottom of the build process:
![image](https://github.com/vHeemstra/vite-plugin-imagemin/assets/23612546/d49c633c-05ce-4e33-98ba-4b7b1435e539)

**Comment by vHeemstra** [comment]
Hi @NamesMT, true. In the latest patch version I tried to move as much of the logs to stay with the general output (see image below).

![image](https://github.com/vHeemstra/vite-plugin-imagemin/assets/17368112/5fa69959-0a6e-47c0-8bab-e7e80b977e83)

**Only the input files that have reading errors of unsupported file formats (Animated PNGs for example) will have their log lines at the end.**

This is because of two reasons:
1. Due to how the process is implemented for speed optimizations.
If something goes wrong during reading of the input file, the processing of that file (and any AVIF/WebP output variants) is stopped right then. (We don't have to see the same reading error of a input file for all its output files.)
2. As these errors should be the exception, having them at the end gives you a quicker overview of these troubled files. And also gives more space to display the errors occurring there (see image below). (Which would otherwise mess up the readability of the logs for all other files.)

![image](https://github.com/vHeemstra/vite-plugin-imagemin/assets/17368112/beb6e54a-caa6-4382-bc60-16fc0b8ff0bc)
